
obj-$(CONFIG_TOUCHSCREEN_ILITEK) += ilitek9882x_touch.o
obj-$(CONFIG_TOUCHSCREEN_ILITEK) += ilitek9882x_sprd.o
obj-$(CONFIG_TOUCHSCREEN_ILITEK) += ilitek9882x_node.o
obj-$(CONFIG_TOUCHSCREEN_ILITEK) += ilitek9882x_mp.o
obj-$(CONFIG_TOUCHSCREEN_ILITEK) += ilitek9882x_main.o
obj-$(CONFIG_TOUCHSCREEN_ILITEK) += ilitek9882x_ic.o
obj-$(CONFIG_TOUCHSCREEN_ILITEK) += ilitek9882x_i2c.o
obj-$(CONFIG_TOUCHSCREEN_ILITEK) += ilitek9882x_flash.o

ccflags-y += -I$(srctree)/drivers/input/touchscreen/ilitek/firmware/